---
name: Reusable - Draft Release Notes 📝🎉
run-name: Draft Release Notes 📝🎉

on:
  workflow_call:
    secrets:
      GITHUB_WORKFLOW_TOKEN:
        description: 'The GITHUB_TOKEN for authentication.'
        required: true

jobs:
  draft-release-notes:
    name: Draft Release Notes 📝🎉
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    steps:
      # Drafts your next Release notes as Pull Requests are merged
      # https://github.com/marketplace/actions/release-drafter
      - name: Draft Release Notes 📝🎉
        id: release-drafter
        uses: release-drafter/release-drafter@6db134d15f3909ccc9eefd369f02bd1e9cffdf97 # v6.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_WORKFLOW_TOKEN }}
