---
name: Reusable - Lint Actions 🧐📜🔍
run-name: Lint Actions 🧐📜🔍

on:
  workflow_call:
    inputs:
      pyflakes_enabled:
        description: 'Enable pyflakes for actionlint (true/false)'
        required: false
        default: false
        type: boolean
      ref:
        description: 'Ref to checkout.'
        required: true
        type: string
      shellcheck_enabled:
        description: 'Enable shellcheck for actionlint (true/false)'
        required: false
        default: true
        type: boolean
      workflow_files:
        description: 'Glob pattern for workflow files to lint.'
        required: false
        default: '.github/workflows/*.yaml,.gitea/workflows/*.yaml'
        type: string
    secrets:
      GITHUB_WORKFLOW_TOKEN:
        description: 'The GITHUB_TOKEN for authentication.'
        required: true

jobs:
  lint-actions:
    name: Lint Actions with ${{ matrix.linter }} 🧐📜🔍
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      # for actions/checkout to fetch code
      contents: read
      # required to upload results to advanced security.
      security-events: write
      # only required for a private repository by zizmorcore/zizmor-action to get the Action run status
      actions: read
    strategy:
      matrix:
        linter: [Actionlint, Zizmor]
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Check Out Repository Code 🛒
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false
          token: ${{ secrets.GITHUB_WORKFLOW_TOKEN }}

      # https://github.com/marketplace/actions/actionlint
      - name: Run Actionlint ✍️
        id: actions-linter-actionlint
        if: ${{ matrix.linter == 'Actionlint' }}
        uses: raven-actions/actionlint@205b530c5d9fa8f44ae9ed59f341a0db994aa6f8 # v2.1.2
        with:
          matcher: true
          files: ${{ inputs.workflow_files }}
          group-result: true
          fail-on-error: true
          shellcheck: ${{ inputs.shellcheck_enabled }}
          pyflakes: ${{ inputs.pyflakes_enabled }}
          cache: true
          github-token: ${{ secrets.GITHUB_WORKFLOW_TOKEN }}

      # https://github.com/marketplace/actions/zizmor-action
      - name: Run Zizmor 🛡️
        id: actions-linter-zizmor
        if: ${{ matrix.linter == 'Zizmor' }}
        uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d # v0.5.0
        with:
          online-audits: true
          token: ${{ secrets.GITHUB_WORKFLOW_TOKEN }}
          advanced-security: true
